config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'charges/create/:id', to: 'charges#create', as: 'charges_with_meetup_id'
  get 'charges/confirmation/:id', to: 'charges#confirmation', as: 'charges_confirmation'
  resources :charges, only: :new

  get 'meetups/new/:type', to: 'meetups#new', as: 'new_meetup_with_type'
  post 'meetups/join_meetup/:id', to: 'meetups#join_meetup', as: 'join_meetup'
  post 'meetups/create/:type', to: 'meetups#create', as: 'create_meetup_with_type'
  patch 'meetups/create/:id', to: 'meetups#update', as: 'patch_meetup_with_type'
  resources :meetups

  post 'comments/add_comment/:id', to: 'comments#add_comment', as: 'add_comment'
  resources :comments, defaults: { format: 'json' }

  get 'users/new_diver', to: 'users#new_diver', as: 'divers_reg'
  post 'users/register_diver', to: 'users#register_diver', as: 'register_diver'

  get 'users/new_instructor', to: 'users#new_instructor', as: 'instructors_reg'
  post 'users/register_instructor', to: 'users#register_instructor', as: 'register_instructor'

  get '/admins', to: 'admins#index'

  get '/admins/edit_permissions', to: 'admins#edit_permissions', as: 'edit_permissions'
  put '/admins/edit_permissions/:id', to: 'admins#update_permissions', as: 'update_permissions'

  get 'home/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "home#index"
end

app/models/abletoteach.rb
class Abletoteach < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certagency.rb
class Certagency < ApplicationRecord
  has_many :divers
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_rich_text :content

  has_many :meetupcomments
  has_many :meetups, through: :meetupcomments
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :certagency

  has_many :abletoteaches
  has_many :instructors, through: :abletoteaches
end

app/models/diver.rb
class Diver < ApplicationRecord
  belongs_to :certagency
  belongs_to :user
  belongs_to :qualification
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :certagency
  belongs_to :user

  has_many :abletoteaches
  has_many :courses, through: :abletoteaches

  accepts_nested_attributes_for :courses
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_rich_text :description

  scope :meetup_type, ->(meetup_type) { where("LOWER(meetup_type) like ?", "%#{meetup_type.downcase}%") }

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode, :if => :address_changed?     # auto-fetch coordinates

  has_many :meetupmembers
  has_many :users, through: :meetupmembers

  has_many :meetupcomments
  has_many :comments, through: :meetupcomments

  def full_street_address
    "#{street_address.titleize}, #{city.titleize}, #{state.titleize}, #{country.upcase}"
  end

  def address_changed?
    attrs = %w(street_address city state country)
    attrs.any? { |a| send "#{a}_changed?" }
  end

  def convert_price_to_cents(price)
    self.price * 100
  end
end

app/models/meetupcomment.rb
class Meetupcomment < ApplicationRecord
  belongs_to :meetup
  belongs_to :comment
end

app/models/meetupmember.rb
class Meetupmember < ApplicationRecord
  belongs_to :meetup
  belongs_to :user
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  has_many :divers
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/skipper.rb
class Skipper < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  attr_accessor :input_roles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable

  mount_uploader :image, ImageUploader

  has_one_attached :image

  accepts_nested_attributes_for :roles

  has_many :meetupmembers
  has_many :meetups, through: :meetupmembers
  has_one :instructor
  has_one :skipper
  has_one :diver
  has_many :comments
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admins/edit_permissions.html.erb
<div class="form-background">
  <div class="form-wrapper">
    <h1 class="form-heading">Control access for users</h1>
    <% @users.each do |user| %>
      <p>
        <strong><%= user.email %></strong>
        <%= form_for user, url: update_permissions_path(user), :method => :put do |f| %>
          <% Role.all.each do |role| %>
            <% if (role.name == "admin") && (user.has_role? :admin) %>
              <%= f.check_box :input_roles, { multiple: true, checked: true }, role.name, nil %>
            <% elsif (role.name == "disabled") && (user.has_role? :disabled) %>
              <%= f.check_box :input_roles, { multiple: true, checked: true }, role.name, nil %>
            <% elsif (role.name == "normal") && (user.has_role? :normal) %>
              <%= f.check_box :input_roles, { multiple: true, checked: true, disabled: true }, role.name, nil %>
            <% elsif (role.name == "normal") && (!(user.has_role? :normal)) %>
              <%= f.check_box :input_roles, { multiple: true, disabled: true }, role.name, nil %>
            <% else %>
              <%= f.check_box :input_roles, { multiple: true }, role.name, nil %>
            <% end %>
            <%= role.name %>
          <% end %>
          <%= f.submit "Change", data: { confirm: "Are you sure you want to make this change for user: #{user.email}" }, :class => "button is-danger" %>
        <% end %>
        <br />
      </p>
    <% end %>
  </div>
</div>

app/views/admins/index.html.erb
<div class="admin-background">
  <div class="admin-wrapper">
    <h1 class="admin-heading">Admins</h1>
    <p>
      <%= link_to "Control access for users", edit_permissions_path, :class => "button is-danger" %>
    </p>
  </div>
</div>

app/views/layouts/_defaultfoot.html.erb
<div class="hero-foot">
  <nav class="tabs">
    <div class="container">
      <p>Icons used designed by Roundicons, sourced from: <a href="https://flaticon.com">flaticon.com</a></p>
    </div>
  </nav>
</div>

app/views/layouts/_defaulthead.html.erb
    <title>Bubble Buddies</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link href="https://fonts.googleapis.com/css?family=Patua+One" rel="stylesheet">
<%= favicon_link_tag image_url("favicon.ico"), :rel => "icon", :type => "image/x-icon" %>
<%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
<%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.credentials[:GOOGLE_API_KEY] || ENV["GOOGLE_API_KEY"] %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'></script>
<script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    // Add smooth scrolling to all # links
    $('a[href*="#"]').on('click', function(event) {

      // Make sure this.hash has a value before overriding default behavior
      if (this.hash !== "") {
        // Prevent default anchor click behavior
        event.preventDefault();

        // Store hash
        var hash = this.hash;

        // Using jQuery's animate() method to add smooth page scroll
        // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
        $('html, body').animate({
            scrollTop: $(hash).offset().top
        }, 800, function() {

            // Add hash (#) to URL when done scrolling (default click behavior)
            window.location.hash = hash;
        });
      } // End if
    });

  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "/layouts/defaulthead" %>
  </head>
  <body>
    <script>
      //document.addEventListener('DOMContentLoaded', function () {
      $(document).ready(function() {

        // Get all "navbar-burger" elements
        var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

          // Add a click event on each of them
          $navbarBurgers.forEach(function ($el) {
            $el.addEventListener('click', function () {

              // Get the target from the "data-target" attribute
              var target = $el.dataset.target;
              var $target = document.getElementById(target);

              // Toggle the class on both the "navbar-burger" and the "navbar-menu"
              $el.classList.toggle('is-active');
              $target.classList.toggle('is-active');

            });
          });
        }

      });
    </script>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="../">
          <%= image_tag "css/navbar_brand.png" %>
        </a>
        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="navMenu">
        <div class="navbar-end">
          <%= image_tag "css/bubbles_edit.png" %>
          <%= link_to "Home", home_index_path, :class => "navbar-item" %>
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, :class => "navbar-item", method: :delete %>
            <%= link_to "Account Settings", edit_user_registration_path, :class => "navbar-item" %>
            <%= link_to "View existing meetups", meetups_path, :class => "navbar-item" %>
            <% if current_user.has_role? :admin %>
              <%= link_to "Admin Settings", admins_path, :class => "navbar-item warning-link" %>
            <% end %>
          <% else %>
            <%= link_to "Login", new_user_session_path, :class => "navbar-item" %>
            <%= link_to "Register", new_user_registration_path, :class => "navbar-item" %>
          <% end %>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render partial: "/layouts/defaultfoot" %>
  </body>
</html>

app/views/layouts/create_charge_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "/layouts/defaulthead" %>
    <script>
      function autoSubmit() {
        document.getElementById("join_meetup_button").click();
      }
      setTimeout(autoSubmit, 4000);
    </script>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render partial: "/layouts/defaultfoot" %>
  </body>
</html>