config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'charges/create/:id', to: 'charges#create', as: 'charges_with_meetup_id'
  get 'charges/confirmation/:id', to: 'charges#confirmation', as: 'charges_confirmation'
  resources :charges, only: :new

  get 'meetups/new/:type', to: 'meetups#new', as: 'new_meetup_with_type'
  post 'meetups/join_meetup/:id', to: 'meetups#join_meetup', as: 'join_meetup'
  post 'meetups/create/:type', to: 'meetups#create', as: 'create_meetup_with_type'
  patch 'meetups/create/:id', to: 'meetups#update', as: 'patch_meetup_with_type'
  resources :meetups

  post 'comments/add_comment/:id', to: 'comments#add_comment', as: 'add_comment'
  resources :comments, defaults: { format: 'json' }

  get 'users/new_diver', to: 'users#new_diver', as: 'divers_reg'
  post 'users/register_diver', to: 'users#register_diver', as: 'register_diver'

  get 'users/new_instructor', to: 'users#new_instructor', as: 'instructors_reg'
  post 'users/register_instructor', to: 'users#register_instructor', as: 'register_instructor'

  get '/admins', to: 'admins#index'

  get '/admins/edit_permissions', to: 'admins#edit_permissions', as: 'edit_permissions'
  put '/admins/edit_permissions/:id', to: 'admins#update_permissions', as: 'update_permissions'

  get 'home/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "home#index"
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_rich_text :description

  scope :meetup_type, ->(meetup_type) { where("LOWER(meetup_type) like ?", "%#{meetup_type.downcase}%") }

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode, :if => :address_changed?     # auto-fetch coordinates

  has_many :meetupmembers
  has_many :users, through: :meetupmembers

  has_many :meetupcomments
  has_many :comments, through: :meetupcomments

  def full_street_address
    "#{street_address.titleize}, #{city.titleize}, #{state.titleize}, #{country.upcase}"
  end

  def address_changed?
    attrs = %w(street_address city state country)
    attrs.any? { |a| send "#{a}_changed?" }
  end

  def convert_price_to_cents(price)
    self.price * 100
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :set_meetup, only: [:show, :edit, :update, :destroy]
  before_action :disallow_disabled

  helper_method :is_instructor?
  helper_method :is_registered_as_diver_or_instructor?

  # GET /meetups or /meetups.json
  def index
    @meetups = Meetup.all

    filter_params.each do |key, value|
      @meetups = @meetups.public_send(key, value) if value.present?
    end

    if (user_signed_in?)
      @registered_diver = Diver.where(user_id: current_user.id).first
      @registered_instructor = Instructor.where(user_id: current_user.id).first
    else
      @registered_diver = nil
      @registered_instructor = nil
    end
  end

  # GET /meetups/1 or /meetups/1.json
  def show
    @meetup = Meetup.find(params[:id])
    @comment = Comment.new
  end

  # GET /meetups/new
  def new
    @meetup = Meetup.new

    if !(is_valid_user_type?)
      respond_to do |format|
        format.html { redirect_to meetups_path, notice: "You cannot create a meetup of that user type" }
      end
    end
  end

  # GET /meetups/1/edit
  def edit
    @meetup = Meetup.find(params[:id])
  end

  # POST /meetups or /meetups.json
  def create
    @meetup = Meetup.new(meetup_params)

    has_errored = false
    if params[:type] == "diver"
      @meetup.meetup_type = "diver"
    elsif params[:type] == "instructor"
      @meetup.meetup_type = "instructor"
    else
      respond_to do |format|
        has_errored = true
        format.html { redirect_to new_meetup_with_type_path(params[:type]), alert: "Meetup type must be of type diver or instructor" }
      end
    end

    if !(has_errored)
      if (params[:meetup][:name] == nil || params[:meetup][:name] == "") || (params[:meetup][:description] == nil || params[:meetup][:description] == "")
        respond_to do |format|
          has_errored = true
          format.html { redirect_to new_meetup_with_type_path(params[:type]), alert: "Please enter both a name and description for your meetup" }
        end
      end
    end

    if !(has_errored)
      if !(params[:meetup][:member_limit].to_i > 0)
        respond_to do |format|
          has_errored = true
          format.html { redirect_to new_meetup_with_type_path(params[:type]), alert: "Please enter a member limit to this meetup, greater than 0" }
        end
      end
    end

    if !(has_errored)
      if is_diver?
        @meetup.price = 0
      elsif params[:meetup][:price] == nil || params[:meetup][:price] == ""
        respond_to do |format|
          has_errored = true
          format.html { redirect_to new_meetup_with_type_path(params[:type]), alert: "Please specify how much you want to charge for the course" }
        end
      end
    end

    if !(has_errored)
      respond_to do |format|
        if @meetup.save
          Meetupmember.create({ meetup_id: @meetup.id, user_id: current_user.id, is_owner: true, can_edit: true })

          format.html { redirect_to meetup_path(@meetup.id), notice: "Meetup was successfully created." }
          format.json { render :show, status: :created, location: @meetup }
        else
          format.html { render :new }
          format.json { render json: @meetup.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /meetups/1 or /meetups/1.json
  def update
    @meetup.meetupmembers.each do |member|
      if (member.user_id == current_user.id) && (member.can_edit == true)
        respond_to do |format|
          if @meetup.update(meetup_params)
            format.html { redirect_to @meetup, notice: "Meetup was successfully updated." }
            format.json { render :show, status: :ok, location: @meetup }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @meetup.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to @meetup, notice: "You do not have permission to edit this meetup" }
        end
      end
    end
  end

  def join_meetup
    if !(is_registered_as_diver_or_instructor?)
      respond_to do |format|
        format.html { redirect_to meetups_path, notice: "You must register yourself as a diver or instructor before joining" }
      end
    else
      if Meetupmember.where("meetup_id = ? and user_id = ?", params[:id], current_user.id).first != nil
        respond_to do |format|
          format.html { redirect_to meetups_url, notice: "You are already already a member of this meetup" }
          format.json { head :no_content }
        end
      else

        #check for payment here

        Meetupmember.create({ meetup_id: params[:id], user_id: current_user.id, is_owner: false, can_edit: false })
        respond_to do |format|
          format.html { redirect_to meetup_path(params[:id]), notice: "Success! You are now attending this meetup!" }
          format.json { head :no_content }
        end
      end
    end
  end

  # DELETE /meetups/1 or /meetups/1.json
  def destroy
    if user_signed_in?
      @meetupmember = Meetupmember.where("meetup_id = ? and user_id = ? and can_edit = ?", params[:id], current_user.id, true).first
      if @meetupmember != nil
        @members_of_meetup = Meetupmember.where(meetup_id: params[:id])
        @members_of_meetup.each do |meetup|
          meetup.destroy
        end

        @meetup.destroy
        respond_to do |format|
          format.html { redirect_to meetups_url, notice: "Meetup was successfully destroyed." }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to meetups_url, notice: "You are not authorised to delete this meetup" }
          format.json { head :no_content }
        end
      end
    end
  end

  def is_diver?
    if params[:type] == "diver"
      return true
    end
    return false
  end

  def is_instructor?
    if params[:type] == "instructor"
      return true
    end
    return false
  end

  def is_registered_as_diver_or_instructor?
    diver = Diver.where("user_id = ?", current_user.id).first
    instructor = Instructor.where("user_id = ?", current_user.id).first

    if diver == nil && instructor == nil
      return false
    end
    return true
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meetup
    @meetup = Meetup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meetup_params
    params.require(:meetup).permit(:name, :description, :is_commercial_trip, :street_address, :city, :state, :country, :is_boat_required, :price, :member_limit, :date, :latitude, :longitude)
  end

  def is_valid_user_type?
    if params[:type] != "diver" && params[:type] != "instructor"
      return false
    end
    return true
  end

  def disallow_disabled
    if user_signed_in?
      if current_user.has_role? :disabled
        respond_to do |format|
          format.html { redirect_to home_index_path, alert: "Your account has been disabled" }
        end
      end
    end
  end

  def filter_params
    # slice will elimate anything from the params hash that doesn't include the following
    params.slice(:meetup_type)
  end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/_form.html.erb
<%= form_with(model: meetup, local: true, url: create_meetup_with_type_path(params[:type])) do |form| %>
  <% if meetup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>
      <ul>
        <% meetup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name, :class => "label" %>
    <div class="control">
      <%= form.text_field :name %>
    </div>
  </div>
  <div class="field">
    <%= form.label :description, :class => "label" %>
    <div class="control">
      <%= form.rich_text_area :description %>
    </div>
  </div>
  <div class="field">
    <%= form.label :is_commercial_trip, :class => "label" %>
    <div class="control">
      <%= form.check_box :is_commercial_trip %>
    </div>
  </div>
  <div class="field">
    <%= form.label :street_address, :class => "label" %>
    <div class="control">
      <%= form.text_field :street_address %>
    </div>
  </div>
  <div class="field">
    <%= form.label :city, :class => "label" %>
    <div class="control">
      <%= form.text_field :city %>
    </div>
  </div>
  <div class="field">
    <%= form.label :state, :class => "label" %>
    <div class="control">
      <%= form.text_field :state %>
    </div>
  </div>
  <div class="field">
    <%= form.label :country, :class => "label" %>
    <div class="control">
      <%= form.text_field :country %>
    </div>
  </div>
  <div class="field">
    <%= form.label :is_boat_required, :class => "label" %>
    <div class="control">
      <%= form.check_box :is_boat_required %>
    </div>
  </div>
  <% if is_instructor? %>
    <div class="field">
      <%= form.label :price, :class => "label"  %>
      <div class="control">
        <%= form.text_field :price %>
      </div>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :member_limit, :class => "label" %>
    <div class="control">
      <%= form.number_field :member_limit %>
    </div>
  </div>
  <div class="field">
    <%= form.label :date, :class => "label" %>
    <div class="control">
      <%= form.datetime_select :date %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit "Create Meetup", :class => "button is-primary" %>
  </div>
<% end %>

app/views/meetups/edit.html.erb
<div class="form-background">
  <div class="form-wrapper">
    <h1 class="form-heading">Editing Meetup</h1>
    <%= form_with(model: @meetup, local: true, url: patch_meetup_with_type_path(@meetup.id)) do |form| %>
      <% if @meetup.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>
          <ul>
            <% @meetup.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :name, :class => "label" %>
        <div class="control">
          <%= form.text_field :name %>
        </div>
      </div>
      <div class="field">
        <%= form.label :description, :class => "label" %>
        <div class="control">
          <%= form.rich_text_area :description %>
        </div>
      </div>
      <div class="field">
        <%= form.label :is_commercial_trip, :class => "label" %>
        <div class="control">
          <%= form.check_box :is_commercial_trip %>
        </div>
      </div>
      <div class="field">
        <%= form.label :street_address, :class => "label" %>
        <div class="control">
          <%= form.text_field :street_address %>
        </div>
      </div>
      <div class="field">
        <%= form.label :city, :class => "label" %>
        <div class="control">
          <%= form.text_field :city %>
        </div>
      </div>
      <div class="field">
        <%= form.label :state, :class => "label" %>
        <div class="control">
          <%= form.text_field :state %>
        </div>
      </div>
      <div class="field">
        <%= form.label :country, :class => "label" %>
        <div class="control">
          <%= form.text_field :country %>
        </div>
      </div>
      <div class="field">
        <%= form.label :is_boat_required, :class => "label" %>
        <div class="control">
          <%= form.check_box :is_boat_required %>
        </div>
      </div>
      <% if is_instructor? %>
        <div class="field">
          <%= form.label :price, :class => "label"  %>
          <div class="control">
            <%= form.number_field :price %>
          </div>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :member_limit, :class => "label" %>
        <div class="control">
          <%= form.number_field :member_limit %>
        </div>
      </div>
      <div class="field">
        <%= form.label :date, :class => "label" %>
        <div class="control">
          <%= form.datetime_select :date %>
        </div>
      </div>
      <div class="actions">
        <%= form.submit "Edit Meetup", :class => "button is-primary" %>
      </div>
    <% end %>
    <%= link_to 'Show', @meetup, :class => "default-scaffold-links"%> |
    <%= link_to 'Back', meetups_path, :class => "default-scaffold-links" %>
  </div>
</div>

app/views/meetups/index.html.erb
<h1 class="meetups-heading">View Existing Meetups</h1>
<% if !(@meetups.any?) %>
  <div class="no-meetups-error">
    <h2>No meetups exist yet. Why not be the first to create one! :)</h2>
  </div>
  <div class="no-meetups-clear-filter-container">
    <%= link_to 'Clear Filters', meetups_path, class: "button is-info" %>
  </div>
<% else %>
  <form>
    <div class="field">
      <p class="bold"><label for="Meetup Type">Filter by Meetup Type:</label></p>
      <div>
        <select name="meetup_type" class="align-filter">
          <option value="diver">Meetups by other dive buddies</option>
          <option value="instructor">Meetups by instructors (for courses)</option>
        </select>
        <input type="submit" value="Filter" class="button is-primary">
        <%= link_to 'Clear Filters', meetups_path, class: "button is-info" %>
      </div>
    </div>
  </form>
  <table class="table is-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Is this a commercial trip?</th>
        <th>Meetup Type</th>
        <th>Meeting Address</th>
        <th>Meeting City</th>
        <th>Meeting State</th>
        <th>Meeting Country</th>
        <th>Is a boat required?</th>
        <th>Price</th>
        <th>Member limit</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @meetups.each do |meetup| %>
        <tr>
          <td class="bold"><%= link_to meetup.name, meetup %></td>
          <% if meetup.is_commercial_trip %>
            <td>Yes</td>
          <% else %>
            <td>No</td>
          <% end %>
          <% if meetup.meetup_type == "diver" %>
            <td class="bold">I'm looking for buddies</td>
          <% elsif meetup.meetup_type == "instructor" %>
            <td class="bold">I'm looking to teach</td>
          <% end %>
          <td><%= meetup.street_address %></td>
          <td><%= meetup.city %></td>
          <td><%= meetup.state %></td>
          <td><%= meetup.country %></td>
          <td><%= meetup.is_boat_required %></td>
          <% if meetup.price == 0 %>
            <td>$0</td>
          <% else %>
            <td class="bold">$<%=sprintf('%02.f', meetup.price)%></td>
          <% end %>
          <td><%= meetup.member_limit %></td>
          <td><%= meetup.date %></td>
          <td><%= link_to 'View Meetup', meetup, :class => "button is-primary" %></td>
          <% if user_signed_in? %>
            <% if meetup.meetupmembers.each do |meetupmember| %>
              <% if (current_user.id == meetupmember.user_id) && (meetupmember.can_edit == true) %>
                <td><%= link_to 'Edit', edit_meetup_path(meetup), :class => "button is-warning" %></td>
                <td><%= link_to 'Destroy', meetup, method: :delete, data: { confirm: 'Are you sure you want to delete this meetup?' }, :class => "button is-danger" %></td>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>
<% if user_signed_in? %>
  <section class="cards-container">
    <div class="section cards" id="cards">
      <div class="container">
        <div class="columns is-multiline">
          <% if @registered_diver == nil  %>
            <div class="column xpro2 is-quarter">
              <p>Click to register as a DIVER!</p>
              <%= image_tag('diver-icon.png', alt: "Diver Icon") %>
              <%= link_to "", divers_reg_path, :class => "card-wrap" %>
            </div>
          <% elsif @registered_diver != nil  %>
            <div class="column xpro2 is-quarter">
              <p>Click to CREATE A MEETUP as a diver looking for buddies or an instructor</p>
              <%= image_tag('diver-icon.png', alt: "Diver Icon") %>
              <%= link_to "", new_meetup_with_type_path("diver"), :class => "card-wrap" %>
            </div>
          <% end %>
          <% if @registered_instructor == nil  %>
            <div class="column xpro2 is-quarter">
              <p>Click to register as an INSTRUCTOR!</p>
              <%= image_tag('instructor-icon.png', alt: "Instructor Icon") %>
              <%= link_to "", instructors_reg_path, :class => "card-wrap" %>
            </div>
          <% elsif @registered_instructor != nil  %>
            <div class="column xpro2 is-quarter">
              <p>Click to CREATE A MEETUP as a instructor looking to teach</p>
              <%= image_tag('instructor-icon.png', alt: "Instructor Icon") %>
              <%= link_to "", new_meetup_with_type_path("instructor"), :class => "card-wrap" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/meetups/new.html.erb
<div class="form-background">
  <div class="form-wrapper">
    <h1 class="form-heading">New Meetup</h1>
    <%= render 'form', meetup: @meetup %>
    <%= link_to 'Back', meetups_path, :class => "default-scaffold-links" %>
  </div>
</div>

app/views/meetups/show.html.erb
<section class="main-content columns is-fullheight custom-background-color">
  <aside class="column is-2 is-narrow-mobile is-fullheight section">
    <h2 class="title is-2">Buddies Attending: <%= image_tag "css/bubbles_edit.png", :class => "attending-bubbles" %></h2>
    <% @meetup.users.each do |user| %>
      <div class="card attending-resize card-bottom-margin">
        <div class="card-image">
          <figure class="image is-4by3">
            <%= image_tag user.image_url %>
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"><%= user.first_name %> <%= user.last_name %> </p>
              <p class="subtitle is-6"><%= user.email %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </aside>
  <div class="container column is-10">
    <h1 class="show-meetup-heading">Meetup:</h1>
    <div class="show-meetup-content-wrapper">
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p>
                <h2 class="show-meetup-name black-text"><%= @meetup.name %></h2>
                <% owner_id = @meetup.meetupmembers.where("meetup_id = ? and is_owner = ?", @meetup.id, "true").first %>
                <% owner = User.find(owner_id.user_id) %>
                <p>By <%= owner.first_name %> <%= owner.last_name %></p>
                <br>
                <br>
                <p class="black-text">
                  <strong>Details:</strong>
                  <%= @meetup.description %>
                </p>
              </p>
            </div>
          </div>
        </article>
      </div>
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p>
                <h3 class="black-text">Important Information:</h3>
                <p>
                  <strong>Is this a commercial trip?</strong>
                  <% if @meetup.is_commercial_trip == false %>
                    No
                  <% else %>
                    Yes
                  <% end %>
                </p>
                <h4 class="black-text">Meeting Location:</h4>
                <% if !((@meetup.street_address == "") && (@meetup.city == "") && (@meetup.state == "") && (@meetup.country == "")) %>
                  <p>
                    <strong>Street address:</strong>
                    <%= @meetup.street_address.titleize %>
                  </p>
                  <p>
                    <strong>City:</strong>
                    <%= @meetup.city.titleize %>
                  </p>
                  <p>
                    <strong>State:</strong>
                    <%= @meetup.state.upcase %>
                  </p>
                  <p>
                    <strong>Country:</strong>
                    <%= @meetup.country.titleize %>
                  </p>
                  <div class='meetup-show-map'>
                    <h4>(Map display currently unavailable due to external API prices)</h4>
                    <% # <div id="map" class='meetup-show-map'></div> %>
                  </div>
                <% else %>
                  <p class="no-location-warning">No meetup location has been specified!</p>
                <% end %>
                <h4 class="black-text">Meeting Time:</h4>
                <h5>
                  <%= @meetup.date %>
                </h5>
                <p>
                  <strong>Is a boat required? (for non-commercial trips)</strong>
                  <% if @meetup.is_boat_required %>
                    Yes
                  <% else %>
                    No
                  <% end %>
                </p>
                <p>
                  <strong>Member limit:</strong>
                  <%= @meetup.member_limit %> people
                </p>
              </p>
            </div>
          </div>
        </article>
      </div>
      <% if user_signed_in? %>
        <% is_joined = false %>
        <% @meetup.meetupmembers.each do |member| %>
          <% if current_user.id == member.user_id %>
            <% is_joined = true %>
            <% if member.can_edit == true %>
              <td><%= link_to "Edit Meetup", edit_meetup_path(@meetup), :class => "button is-warning" %></td>
              <td><%= link_to "Destroy Meetup", @meetup, method: :delete, data: { confirm: "Are you sure you want to delete this meetup?" }, :class => "button is-danger" %></td>
            <% end %>
          <% end %>
        <% end %>
        <% if !(is_joined) %>
          <% if @meetup.meetup_type == "diver" %>
            <% if !is_registered_as_diver_or_instructor? %>
              <div class="box show-meetup-box-width-custom">
                <article class="media">
                  <div class="media-content">
                    <div class="content">
                      <p><%= link_to "Please register as a diver", divers_reg_path, :class => "button is-info" %> and/or <%= link_to "please register as an instructor", instructors_reg_path, :class => "button is-info" %> to join this meetup! </p>
                    </div>
                  </div>
                </article>
              </div>
            <% else %>
              <%= link_to "Join This Meetup :)", join_meetup_path(@meetup.id), method: :post, :class => "button is-primary" %>
            <% end %>
          <% else %>
            <% if !is_registered_as_diver_or_instructor? %>
              <div class="box show-meetup-box-width-custom">
                <article class="media">
                  <div class="media-content">
                    <div class="content">
                      <p><%= link_to "Please register as a diver", divers_reg_path, :class => "button is-info" %> and/or <%= link_to "please register as an instructor", instructors_reg_path, :class => "button is-info" %> to join this meetup! </p>
                    </div>
                  </div>
                </article>
              </div>
            <% else %>
              <div class="box show-meetup-box-width-custom">
                <article class="media">
                  <div class="media-content">
                    <div class="content">
                      <h3 class="black-text">Price:</h3>
                      <h4>$<%= "%.2f" % @meetup.price %></h4>
                      <%= form_tag charges_with_meetup_id_path(@meetup.id) do |f| %>
                        <article>
                          <% if flash[:error].present? %>
                            <div id="error_explanation">
                              <p><%= flash[:error] %></p>
                            </div>
                          <% end %>
                        </article>
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Join this meetup"
              data-email="<%= current_user.email %>"
              data-label="Pay and Join This Meetup"
              data-amount="<%= @meetup.convert_price_to_cents(@meetup.price) %>"
              data-locale="auto"></script>
                      </div>
                    </div>
                  </article>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <h3 class="black-text">Comments:</h3>
              <% @meetup.comments.each do |comment| %>
                <div>
                  <h3><%= comment.user.first_name %> <%= comment.user.last_name %></h3>
                  <p><%= comment.created_at %></p>
                  <p><strong><%= comment.content %></strong></p>
                </div>
              <% end %>
              <% if is_joined == true %>
                <hr/>
                <%= form_for @comment, url: add_comment_path(@meetup.id), :method => :post do |f| %>
                  <div class="control control-left-align">
                    <%= f.label "Add a new comment:", :class => "label" %>
                    <%= f.text_area :content, id: :content %>
                  </div>
                  <%= f.submit "Add Comment" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </article>
      </div>
      <%= link_to "Back", meetups_path, :class => "button is-info" %>
      <script type="text/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({
           provider: {

           },
           internal: {
             id: 'map'
            }
          },
          function(){
          markers = handler.addMarkers([
            {
              "lat": <%= @meetup.latitude %>,
              "lng": <%= @meetup.longitude %>,
              "picture": {
                "url": "http://res.cloudinary.com/chullman/image/upload/v1525666850/map_marker.png",
                "width":  32,
                "height": 32
              },
              "infowindow": "You're meetup location @ <%= @meetup.full_street_address %>"
            }
          ]);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      </script>
    </div>
  </div>
</section>