config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'charges/create/:id', to: 'charges#create', as: 'charges_with_meetup_id'
  get 'charges/confirmation/:id', to: 'charges#confirmation', as: 'charges_confirmation'
  resources :charges, only: :new

  get 'meetups/new/:type', to: 'meetups#new', as: 'new_meetup_with_type'
  post 'meetups/join_meetup/:id', to: 'meetups#join_meetup', as: 'join_meetup'
  post 'meetups/create/:type', to: 'meetups#create', as: 'create_meetup_with_type'
  patch 'meetups/create/:id', to: 'meetups#update', as: 'patch_meetup_with_type'
  resources :meetups

  post 'comments/add_comment/:id', to: 'comments#add_comment', as: 'add_comment'
  resources :comments, defaults: { format: 'json' }

  get 'users/new_diver', to: 'users#new_diver', as: 'divers_reg'
  post 'users/register_diver', to: 'users#register_diver', as: 'register_diver'

  get 'users/new_instructor', to: 'users#new_instructor', as: 'instructors_reg'
  post 'users/register_instructor', to: 'users#register_instructor', as: 'register_instructor'

  get '/admins', to: 'admins#index'

  get '/admins/edit_permissions', to: 'admins#edit_permissions', as: 'edit_permissions'
  put '/admins/edit_permissions/:id', to: 'admins#update_permissions', as: 'update_permissions'

  get 'home/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "home#index"
end

app/models/abletoteach.rb
class Abletoteach < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certagency.rb
class Certagency < ApplicationRecord
  has_many :divers
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_rich_text :content

  has_many :meetupcomments
  has_many :meetups, through: :meetupcomments
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :certagency

  has_many :abletoteaches
  has_many :instructors, through: :abletoteaches
end

app/models/diver.rb
class Diver < ApplicationRecord
  belongs_to :certagency
  belongs_to :user
  belongs_to :qualification
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :certagency
  belongs_to :user

  has_many :abletoteaches
  has_many :courses, through: :abletoteaches

  accepts_nested_attributes_for :courses
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_rich_text :description

  scope :meetup_type, ->(meetup_type) { where("LOWER(meetup_type) like ?", "%#{meetup_type.downcase}%") }

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode, :if => :address_changed?     # auto-fetch coordinates

  has_many :meetupmembers
  has_many :users, through: :meetupmembers

  has_many :meetupcomments
  has_many :comments, through: :meetupcomments

  def full_street_address
    "#{street_address.titleize}, #{city.titleize}, #{state.titleize}, #{country.upcase}"
  end

  def address_changed?
    attrs = %w(street_address city state country)
    attrs.any? { |a| send "#{a}_changed?" }
  end

  def convert_price_to_cents(price)
    self.price * 100
  end
end

app/models/meetupcomment.rb
class Meetupcomment < ApplicationRecord
  belongs_to :meetup
  belongs_to :comment
end

app/models/meetupmember.rb
class Meetupmember < ApplicationRecord
  belongs_to :meetup
  belongs_to :user
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  has_many :divers
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/skipper.rb
class Skipper < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  attr_accessor :input_roles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable

  mount_uploader :image, ImageUploader

  has_one_attached :image

  accepts_nested_attributes_for :roles

  has_many :meetupmembers
  has_many :meetups, through: :meetupmembers
  has_one :instructor
  has_one :skipper
  has_one :diver
  has_many :comments
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @registered_diver = Diver.where(user_id: current_user.id).first
      @registered_instructor = Instructor.where(user_id: current_user.id).first
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certagencies_helper.rb
module CertagenciesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="hero is-large is-bold">
  <div class="hero-body">
    <div class="container has-text-right">
      <div class="top-align-text">
        <h1 class="title">
          For divers of all levels!
        </h1>
        <h2 class="subtitle">
          A friendly meetup platform for divers of all levels to find dive buddies, and for dive instructors to offer their services!
        </h2>
      </div>
    </div>
    <br />
    <div class="container has-text-right">
      <% if !(user_signed_in?) %>
        <a href="<%= new_user_session_path %>" class="button is-large is-info small-margin-top-bottom">Please login or register an account!</a>
      <% elsif user_signed_in? %>
        <% if @registered_diver == nil && @registered_instructor == nil %>
          <a href="#cards" class="button is-large is-info small-margin-top-bottom">Are you a diver or an instructor?</a>
        <% else %>
          <a href="#cards" class="button is-large is-info small-margin-top-bottom">Create a meetup or join an existing one :)</a>
        <% end %>
      <% end %>
    </div>
  </div>
</section>
<% if !(user_signed_in?) %>
  <section class="cards-container">
    <div class="section cards" id="cards">
      <div class="container">
        <div class="columns-for-home is-multiline">
          <div class="column xpro2 is-quarter">
            <p>View EXISTING MEETUPS</p>
            <%= image_tag "meetup-icon.png" %>
            <%= link_to "", meetups_path, :class => "card-wrap" %>
          </div>
        </div>
      </div>
    </div>
  </section>
<% elsif user_signed_in? %>
  <section class="cards-container">
    <div class="section cards" id="cards">
      <div class="container">
        <div class="columns is-multiline">
          <div class="column xpro2 is-quarter">
            <p>View EXISTING MEETUPS</p>
            <%= image_tag "meetup-icon.png" %>
            <%= link_to "", meetups_path, :class => "card-wrap" %>
          </div>
          <% if @registered_diver == nil %>
            <div class="column xpro2 is-quarter">
              <p>Click to register as a DIVER!</p>
              <%= image_tag "diver-icon.png" %>
              <%= link_to "", divers_reg_path, :class => "card-wrap" %>
            </div>
          <% elsif @registered_diver != nil %>
            <div class="column xpro2 is-quarter">
              <p>Click to CREATE A MEETUP as a diver looking for buddies or an instructor</p>
              <%= image_tag "diver-icon.png" %>
              <%= link_to "", new_meetup_with_type_path("diver"), :class => "card-wrap" %>
            </div>
          <% end %>
          <% if @registered_instructor == nil %>
            <div class="column xpro2 is-quarter">
              <p>Click to register as an INSTRUCTOR!</p>
              <%= image_tag "instructor-icon.png", :class => "scale-home-page-card-icon" %>
              <%= link_to "", instructors_reg_path, :class => "card-wrap" %>
            </div>
          <% elsif @registered_instructor != nil %>
            <div class="column xpro2 is-quarter">
              <p>Click to CREATE A MEETUP as a instructor looking to teach</p>
              <%= image_tag "instructor-icon.png", :class => "scale-home-page-card-icon" %>
              <%= link_to "", new_meetup_with_type_path("instructor"), :class => "card-wrap" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
<% end %>